robutler:
  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

  pole_to_claw_right_second_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: pole_to_claw_right_second_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}

  pole_to_claw_left_second_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: pole_to_claw_left_second_joint
      pid: {p: 1.0, i: 1.0, d: 0.0}